In [1]:
import pandas as pd
df_penguins = pd.read_csv('penguins_data.csv')

In [3]:
df_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181,3750,male
1,Adelie,Torgersen,39.5,17.4,186,3800,female
2,Adelie,Torgersen,40.3,18.0,195,3250,female
3,Adelie,Torgersen,36.7,19.3,193,3450,female
4,Adelie,Torgersen,39.3,20.6,190,3650,male
...,...,...,...,...,...,...,...
328,Chinstrap,Dream,55.8,19.8,207,4000,male
329,Chinstrap,Dream,43.5,18.1,202,3400,female
330,Chinstrap,Dream,49.6,18.2,193,3775,male
331,Chinstrap,Dream,50.8,19.0,210,4100,male
332,Chinstrap,Dream,50.2,18.7,198,3775,female

In [5]:
# https://www.kaggle.com/pratik1120/penguin-dataset-eda-classification-and-clustering
df = df_penguins.copy()
target = 'species'
encode = ['sex','island']

In [6]:
# encode columns has categorical variable after encoding it original columns is deleted
for col in encode:
    dummy = pd.get_dummies(df[col], prefix=col)
    df = pd.concat([df,dummy], axis=1)
    del df[col]
    
df.head()

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex_female,sex_male,island_Biscoe,island_Dream,island_Torgersen
0,Adelie,39.1,18.7,181,3750,False,True,False,False,True
1,Adelie,39.5,17.4,186,3800,True,False,False,False,True
2,Adelie,40.3,18.0,195,3250,True,False,False,False,True
3,Adelie,36.7,19.3,193,3450,True,False,False,False,True
4,Adelie,39.3,20.6,190,3650,False,True,False,False,True

In [7]:
target_mapper = {'Adelie':0, 'Chinstrap':1, 'Gentoo':2}
def target_encode(val):
    return target_mapper[val]

In [8]:
df['species'] = df['species'].apply(target_encode)

In [9]:
# Separating X and y
X = df.drop('species', axis=1)
Y = df['species']

In [10]:
# Build random forest model
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X, Y)

RandomForestClassifier()

In [11]:
# Saving the model
import pickle
pickle.dump(clf, open('penguins_clf.pkl', 'wb'))